### ISSUE TITLE
Subscribe component calling setState in render

### ISSUE THREAD

**Issue by tibetsprague** [daostack/alchemy#1020]
e41844836889be3b8d0363ebcf51005047fc9721 causes react warnings, and probably issues by calling setState in render(). this.setupSubscription should be called in an earlier component lifecycle function like componentDidMount

**Comment by jellegerbrandy** [comment]
what kind of warnings? How do you know they are from that commit?

By way of explanation: 

I moved it way from componentwillmount because that hook is deprecated: https://reactjs.org/docs/react-component.html#unsafe_componentwillmount

And I am not calling setState in the render() method in any unrecommended way, I think. What is happening is the the render sets up a new subscrition (if the observable has changed), that subscription will fetch the data and only then reset the state (and re-render()). 

(btw, componentDidMont is not earlier but later in the lifecyle: https://reactjs.org/docs/react-component.html#the-component-lifecycle)

**Comment by dkent600** [comment]
Newbie suggestion:  May be optimal to memoize it?

https://reactjs.org/blog/2018/06/07/you-probably-dont-need-derived-state.html#what-about-memoization

**Comment by jellegerbrandy** [comment]
what is "it" in your suggestion?

**Comment by tibetsprague** [comment]
"componentDidMount() is invoked immediately after a component is mounted (inserted into the tree). Initialization that requires DOM nodes should go here. If you need to load data from a remote endpoint, this is a good place to instantiate the network request.

**This method is a good place to set up any subscriptions. If you do that, don’t forget to unsubscribe in componentWillUnmount().**"

**Comment by jellegerbrandy** [comment]
fixed in #1025
