### ISSUE TITLE
Adding custom tokens to the DAO's token list

### ISSUE THREAD

**Issue by arsena21** [daostack/alchemy#1318]
Below is some of the conversation with @dOrgJelli and @orishim from dOrg...

"Would it be possible to create a scheme which can add a token to the list in a DAO's dropdown? Or do this when you are launching the DAO? http://prntscr.com/qqgoyf "

"the signal scheme would be a great fit for this. Currently they'd have to add the token to this list: https://github.com/daostack/alchemy/blob/dev/data/tokens.json"

"This could be something that's apart of your 3box profile (seems unrelated, but it's basically a place for dApps to store user preferences). What this means is that each user could manually add tokens they care about to alchemy and they'd show up. It's the same thing you do within metamask.
This wouldn't require the signal scheme, and would just be a simple change to alchemy.
*simple ;) not really though"

"I would bring this up to Zak, Tibets, Doug, and Jelle (the alchemy developers) to get this on their radar. Could be very quick for them."

This would be a super useful feature, and something that has been a problem with some use cases so far. 

Thanks,
Eric

**Comment by tibetsprague** [comment]
I'm hearing two different things here. One is a proposal that allows for adding a custom token to a DAO permanently, so all users always see it as an option to reward in that token. 

Secondly you are talking about users adding a token to their own personal list so they always see it in every DAO. 

Is that true @arsena21? Personal token preferences seem easier to add than a proposal type that permanently alters a DAO somehow, because that would require work on the contract level

**Comment by arsena21** [comment]
I’m actually not sure what you mean by the following “ users adding a token
to their own personal list so they always see it in every DAO.”

I was thinking more the first case

**Comment by tibetsprague** [comment]
this part: "This could be something that's apart of your 3box profile (seems unrelated, but it's basically a place for dApps to store user preferences). What this means is that each user could manually add tokens they care about to alchemy and they'd show up. It's the same thing you do within metamask."

**Comment by tibetsprague** [comment]
should probably split this into two tickets
