### ISSUE TITLE
Cannot load dxdao proposal history

### ISSUE THREAD

**Issue by pimato** [daostack/alchemy#1510]
<img width="1192" alt="Screenshot 2020-03-13 at 20 41 46" src="https://user-images.githubusercontent.com/5337809/76654510-66deb980-656b-11ea-8c9f-cfafb4ee1907.png">

**Comment by pimato** [comment]
Link: https://alchemy.daostack.io/dao/0x519b70055af55a007110b4ff99b0ea33071c720a/history/

**Comment by dkent600** [comment]
The crash is on this line in the client lib:  

https://github.com/daostack/client/blob/dfaeeaf9232cc45e6d3607625a156305638da5f7/src/proposal.ts#L543

`schemeState` is null.

I am not sure at this point whether this is a subgraph or a client lib issue.

This subgraph query shows a proposal that fails in this way:

```
	{
	    proposals(where: {id: "0x3eee066c25c29bccc3c7b2135a9078b2018f1d898a0d48998815a1763c1788a2"}) {
	      title, scheme  {
	        id
	      }
	}
  }
```

**Comment by orenyodfat** [comment]
Seems like this case is due a proposal in a scheme which was unregister and its scheme entity was deleted from the subgraph.
- in order to maintain all. proposals history we should not delete controller schemes upon unregiste event.
- `isRegister` field will be added to controllerScheme entity .
- alchemy will show dao's schemes in condition to `isRegister` .
https://github.com/daostack/subgraph/issues/496
