### ISSUE TITLE
update to latest recommended node version 12.6.1

### ISSUE THREAD

**Issue by orenyodfat** [daostack/alchemy#1531]
https://nodejs.org/en/ 
Currently build process failing using it.
This might solve some build issues .

**Comment by dkent600** [comment]
See recommendation here:  https://help.heroku.com/tickets/837443#event_d4c5d3f0-2c91-4b6b-8377-81b86e93033a

After getting the latest node version working, we should investigate reverting "cheap-source-map" to "source-map" in webpack.prod.config.js, as "cheap" compromises our ability to debug.  "cheap-source-map" was put in place to enable heroku review apps to deploy without failing due to out-of-memory.

**Comment by dkent600** [comment]
Getting rid of "cheap" worked briefly with v11.15.0.  But ultimately didn't last long.

**Comment by dkent600** [comment]
#1 hypothesis is that the old version of web3 that the migration package is pulling in is cause most of all of the install errors.

> $ npm list @daostack/migration
alchemy-client@0.10.3 C:\Users\dkent\Documents\Projects\GitHub\DAOStack\alchemy
`-- @daostack/migration@0.0.1-rc.40-v1
>
> $ npm list web3
alchemy-client@0.10.3 C:\Users\dkent\Documents\Projects\GitHub\DAOStack\alchemy
+-- @daostack/client@0.2.64
| `-- web3@1.2.4  deduped
+-- @daostack/migration@0.0.1-rc.40-v1
| `-- web3@1.0.0-beta.37
+-- @dorgtech/daocreator-ui@1.0.6
| `-- @dorgtech/daocreator-lib@1.0.0
|   `-- web3@1.2.4  deduped
+-- @toruslabs/torus-embed@1.2.6
| `-- web3@0.20.7
`-- web3@1.2.4

**Comment by orenyodfat** [comment]
update travis node version

**Comment by dkent600** [comment]
that is weird
