### ISSUE TITLE
DAO front-ends

### ISSUE THREAD

**Issue by arsena21** [daostack/alchemy#1567]
See designs here: https://www.figma.com/file/fq10yjxy4EaaESPzqBGkEG/DAO-front-end

**Comment by EzraWeller** [comment]
# Simple DAO Front-ends
Eric, Eylon, and I view this as a high priority for April. We are seeking feedback from the implementation team on the following plan:
## Summary
The home page for each DAO in Alchemy should more clearly highlight the few simple actions users should take in that DAO. We would like to accomplish this by making each DAO’s homepage a full page with content controlled by the DAO.

This should happen in two stages:
1. Give each DAO a default home page, with default home page content created by us.
2. Give each DAO the ability to change this content via proposal (or the option to add that ability).
## Business Case / Target Audience
This feature should mainly benefit:
- DAOstack and other service providers building on the stack, since it will make active DAOs clearer to understand for anyone new looking at them.
- DAOs looking to onboard new users, since this will let them include the most important information for members clearly and up front.
## User Stories
A new user hits the home page of a DAO in Alchemy. What they see makes it obvious what this DAO is about and how they can take their first actions in the DAO -- whether that means proposing, commenting, voting, or some other action.
## Product Design
[An initial mock up created by Eric](https://www.figma.com/file/fq10yjxy4EaaESPzqBGkEG/DAO-front-end?node-id=0%3A1)

The details here are not final, but this mock does give a fairly clear visual direction.
## Functional Spec
We have the progress made by dOrg and Ape Unit on the DAO wiki and header respectively. We should evaluate if these projects can and should be repurposed for this patch.
### Stage 1: 
Every DAO should be given a simple homepage that lives in the “Home” tab and includes this information:

> [DAO Name]

> Welcome to [DAO name], a decentralized organization built on DAOstack.

> Visit the [Proposals page](link to proposals page) to make a proposal to the DAO or vote on existing proposals.

> Visit the [DAO Wall](link to DAO Wall) to participate in general discussion about this DAO.

The current “Home” tab should be relabeled to “Proposals.” 
### Stage 2:
Create a scheme/plugin called “Edit Homepage” that lets the DAO change the content on its Homepage. 
- This does not need to reuse the DAO wiki or DAO header work, but it can, if they will help (up to the implementation team).
- The main text of the homepage should support markdown or some other rich text that can embed images and videos if at all possible.
- **Key priority**: a full page of editable rich text, where each proposal proposes a full new version of this text, and the DAO displays the most recently passed version.
- Secondary priority: allow the DAO to edit multiple pages like this, perhaps giving each page a tab, or using the default page of the wiki as the homepage itself.

Add to the default DAO homepage a button labeled “Edit this page.” This button should:
- If the DAO has registered the Scheme Registrar, but does not have the new Edit Homepage scheme, the button should take you to the Scheme Registrar and open a new proposal modal, prefilled to propose adding the Edit Homepage scheme (similar to what I believe the [DAO Wiki has done](https://github.com/daostack/alchemy/pull/1314)).
- If the DAO has the Edit Homepage scheme, this button should take you to the page for that scheme and open a new proposal modal.

**Comment by dkent600** [comment]
Stage 1 is definitely doable in April if given top priority.  Stage 2, doubtful.

**Comment by EzraWeller** [comment]
What would be your estimate for stage 2? I think we should simplify it to the point that it is doable by early May at the latest -- I imagine we could do this by just making it a version of the wiki scheme?

**Comment by dkent600** [comment]
> What would be your estimate for stage 2?

@EzraWeller To answer this we (the dev team) need to first need clear up our story on how we are doing custom DAO content in general.

**Comment by dkent600** [comment]
@EzraWeller @arsena21 This should be broken into two separate tickets, one for each phase.

**Comment by EzraWeller** [comment]
Updated stage 1 design here: https://www.figma.com/file/qsog4uCensMYaaSclxlmVi/DAO-Front-End-Mocks?node-id=0%3A1
@dkent600 Let's split this into multiple issues and/or projects once we know a bit more about how stage 2 will work. Working on that next.
