### ISSUE TITLE
"New proposal..." buttons should line up vertically with page

### ISSUE THREAD

**Issue by EzraWeller** [daostack/alchemy#1674]
The "new proposal" buttons should share the margin of the rest of the page (currently looking at release 0.10.6):
<img width="1146" alt="Screen Shot 2020-05-06 at 3 44 40 PM" src="https://user-images.githubusercontent.com/5414803/81221417-cd52e780-8fb0-11ea-811e-d628ec77e806.png">

**Comment by dkent600** [comment]
Broken by: https://github.com/daostack/alchemy/pull/1598

See css.createproposal, it is "fixed" in place (!)

**Comment by dkent600** [comment]
Note that the requested appearance does not conform to what is currently in production:

![image](https://user-images.githubusercontent.com/1821666/81330461-1a48c380-906e-11ea-8a5c-3bc80eb11dd4.png)

**Comment by dkent600** [comment]
To be consistent, making the same layout change and refactor with the Edit Plugin button

![image](https://user-images.githubusercontent.com/1821666/81334766-8a5a4800-9074-11ea-887f-179767991c4b.png)

**Comment by dkent600** [comment]
In terms of code, but not layout, this one should be refactored as well, but will not do it now because I'm afraid it would prevent the PR from being accepted.  But what is nice is that now these buttons will be more consistent in appearance across these pages.

![image](https://user-images.githubusercontent.com/1821666/81335031-f76ddd80-9074-11ea-8d9f-571502f438a2.png)
