### ISSUE TITLE
Creation of DAOs via the DAOcreator on the xDAI network 

### ISSUE THREAD

**Issue by Theylon** [daostack/alchemy#1741]
Currently we are able to deploy DAOs using the DAOcreator on standard main and test networks. 

As gas prices skyrocket resulting in voting transactions to cost $5+ to be mined within an hour, many DAOs are opting for xDAI deployment rather than mainnet. 

Currently xDAI dao deployment is not available through the DAOcreator. According to @dOrgJelli some support is required to add this.

**Comment by dkent600** [comment]
@Theylon 

> some support is required to add this

In Alchemy?  So DaoCreator itself is go-to-go as for as this is concerned?

@dOrgJelli What support is needed?

**Comment by Theylon** [comment]
I think the goal is to use DAOcreator for most needs. 

Gas fees are skyrocketing at the moment and most new DAOs want to initialize on xDAI.

**Comment by dtbx** [comment]
I join @Theylon in requesting support. It's an urgent need, currently multiple DAOpreneurs cannot get their DAO experiments progressed because the Ethereum network is clogged.  Launching a DAO using DAOcreator would usually be easy on main and test networks. 

DAOs will potentially opt to xDAI deployment rather than mainnet to save expenses on gas.

@orishim @dOrgJelli

**Comment by dkent600** [comment]
I have no idea what I meant by "go-to-go" above. Doh.  Bottom line I think it that this work needs to be done in the @orgTech repo.  There is already a ticket on that:  https://github.com/dOrgTech/DAOcreator/issues/387
