### ISSUE TITLE
SearchBar 

### ISSUE THREAD

**Issue by GreyEcologist** [daostack/alchemy#190]
a way for users to search proposals by their title

user story:
- user goes to the alchemy page of a DAO
- a search bar is available on the top part of the page
- a placeholder "search a proposal" text 
- user enters search words 
- user clicks a "search" button to the right on the search bar
- relevant proposals from both active and history are returned

**Comment by jellegerbrandy** [comment]
Clsoing this due to inactivity

**Comment by Theylon** [comment]
Hey @orenyodfat @roienatan @EzraWeller This has been brought up by DXdao as a potential useful feature. 
It's a low hanging fruit, can this be prioritized?

**Comment by dkent600** [comment]
This is unclear as to on which page the search filter should appear.  I think it makes most sense, and is most easily coded, to put it on the proposal history page.   Importantly:  Proposals on that page span all schemes.

However, the request here is asking to include in the search results proposals that are still "active".  The history page currently includes `IProposalStage.ExpiredInQueue, IProposalStage.Executed, IProposalStage.Queued`.  I have no idea why it doesn't display all stages.

Should we make the History page display all proposals instead of filtering out several stages as it does?

@orenyodfat @EzraWeller @Theylon

**Comment by dkent600** [comment]
Reopening for the 2.0 PR
