### ISSUE TITLE
Simple UX changes: Move "Support" link to popup to side menu

### ISSUE THREAD

**Issue by arsena21** [daostack/alchemy#1940]
Remove the big blue "support" button and move it to the side menu. The popup can stay at the same spot.

**Comment by roienatan** [comment]
@arsena21 @dkent600 @orenyodfat 
From my investigation until now, the way we can manipulate the button is limited since it's embedded in zendesk scripts. 
- You can not place the button in one place and open the popup in another place.
- If you place the button "inside" the sidebar it hovers and not really part of the sidebar, meaning it's not responsive for changes and can hide text on the sidebar.

Our options:
- Change the attributes that we can manipulate natively from zendesk (such as color and position. Looks like size is not possible to change)
- Create our "support" button to just trigger the opening of the popup. In that way we can control the button as much as we like but I'm trying to investigate if there is an option to trigger the popup on a custom element.
- Try to modify the button using scss with `!important`. It's not a best practice and I try to avoid using `!important` but it can be a good solution with the least code changes.

**Comment by orenyodfat** [comment]
@arsena21 any insight ?
