### ISSUE TITLE
2.0: wrong vote number

### ISSUE THREAD

**Issue by orenyodfat** [daostack/alchemy#1980]
it say 2 votes though only 1 vote on it :( 

<img width="460" alt="Screen Shot 2020-07-18 at 10 15 51" src="https://user-images.githubusercontent.com/5994398/87847300-c49b5d80-c8df-11ea-8944-ee4ed340d43f.png">

https://alchemy-2-kovan.herokuapp.com/dao/0x790e3ed4b75b357f882cb595b2d233da799a1207/proposal/0x7e0e5a3ad2d3f2ad698a1ee5165a797cbca532503ad4b4ab771b2d01d88a7152

**Comment by roienatan** [comment]
Insights until now:
The `votesCount` is not consistent across Alchemy.
For some reason, when trying to go to that proposal via History page, there is a duplication in the votes (see image) and that's why we see 2 votes - actually it's the same vote counted twice.
If you reach that proposal from a different path (for example refreshing the page) we get 1 vote as expected.
![Capture](https://user-images.githubusercontent.com/34843014/87876946-fd245f80-c9e3-11ea-93bd-ffdc3828499f.JPG)

**Comment by dkent600** [comment]
This really looks like the problem is either in arc.js or thegraph.

**Comment by dkent600** [comment]
Indeed is coming from subgraph:  https://github.com/daostack/subgraph/issues/583

**Comment by dkent600** [comment]
The subgraph PR:  https://github.com/graphprotocol/graph-node/pull/1825
