### ISSUE TITLE
should have a much smaller bundle download footprint

### ISSUE THREAD

**Issue by dkent600** [daostack/alchemy#2015]
Currently one can see in the browser debugger network tab that a full download of [Alchemy 2.0 - rinkeby](https://alchemy-2-rinkeby.herokuapp.com/) is 16.7M.  This is way too much.

However I note that the heroku config for that site is missing the NODE_ENV variable, so don't know for sure if the site is being gzipped, etc.  @orenyodfat

**Comment by orenyodfat** [comment]
what the bundle size of 1.0 ? @dkent600

**Comment by orenyodfat** [comment]
bundle size optimisation ! ?

**Comment by Razzwan** [comment]
Working on it. Partially it was done as a part of this issue: https://github.com/daostack/alchemy/pull/2267

It was 2 times improved, but we still have problems with this library: [@dorgtech/daocreator-ui](https://www.npmjs.com/package/@dorgtech/daocreator-ui). Right now it is loaded async, but we can improve this package itself, because biggest bundl is exaclty this library. Working on it
