### ISSUE TITLE
Queued proposals that time out don't automatically move to history

### ISSUE THREAD

**Issue by tibetsprague** [daostack/alchemy#473]
They stick around in the Queue

**Comment by jellegerbrandy** [comment]
Yes, this is because if we show the page at 10AM, the query says "show me all proposals that timeout before 10AM", and the results of that query do not change at 11AM. We shoudl send a new query instead.

It is a bit of a nasty problem. The solution will be something like: "if a proposal times out, it must renew the subscription of the container it is in (and also of other containers that may change as a result)", I think
