### ISSUE TITLE
Disable voting when the proposal ends

### ISSUE THREAD

**Issue by A-Zak** [daostack/alchemy#514]
After a proposal ends (pass / fail / timeout) the user should not see the voting buttons any more.
Instead of the voting buttons, let's put a note (in a box like the "predictions are disabled") saying "voting is over".

**Comment by tibetsprague** [comment]
Fixed by https://github.com/daostack/alchemy/pull/517 on branch fix_button_states, but @brodeur may want to style differently like you said Alex, hide the buttons completely with some text instead of just disabling them. But we probably want to also tell the user why voting is disabled, maybe with a tooltip. Could be because they have 0 reputation, or for various proposal states or because theyve already voted
