### ISSUE TITLE
support gnosis safe browser extension

### ISSUE THREAD

**Issue by jellegerbrandy** [daostack/alchemy#711]
https://chrome.google.com/webstore/detail/gnosis-safe-mainnet-beta/iecodoenhaghdlpodmhooppdhjhmibde

**Comment by jellegerbrandy** [comment]
for questions: Germán Martinez from gnosis.

**Comment by germartinez** [comment]
Hello and thank you for taking a look at this :)

As a summary, this is the issue we have when trying to use the Safe browser extension with Alchemy Daostack.

The Safe browser extension does not inject a web3provider instantly as MM does, because we do some previous checks (if the curent Dapp is whitelisted or not).

I've been debugging the Alchemy app locally and I found that even if there is a login button, the `web3` and `web3provider` are only setted at the beginning, when the global `arc` object is initialized, before the Gnosis provider is injected.

When the login button is clicked, it checks the `window.ethereum` variable, but `getArc().web3` is still using the same old `web3` setted at the beggining in the constructor, so the function `pollForAccountChanges` never return the right address from the late injected provider.

There is a way to skip this login issue using Ctrl+F5 and then everything seems to work inside the app, but we would like to make use of the login button.

From what I have seen, I think two possible solutions for this could be to add a setter in the `Arc` class from the project `daostack/client` to allow the update of the `web3` with a `web3provider` as an argument and calling it from the `handleClickLogin` function in the Alchemy app, or to reinitialize the global `arc` object in the `handleClickLogin` like it's done in the `AppContainer.tsx` at the very beginning.

**Comment by leviadam** [comment]
Implemented in #872
