### ISSUE TITLE
redeem for beneficiary button - wrong beneficiary 

### ISSUE THREAD

**Issue by orenyodfat** [daostack/alchemy#732]
expected : 
`redeem for beneficiary` should call redeemer.redeem with  the beneficiary  as the 3rd param. 

found : 
`redeem for beneficiary` call redeemer.redeem with  the account which connect to meta mask  as the beneficiary.

**Comment by jellegerbrandy** [comment]
If this is a bug, it seems to me more of a UX bug :-)

What is intended by "redeem for beneficiary" is that by clicking on that button, the rewards of the contributionreward will be transfered for the benficiary of that ContributionReward.

It is just a label on the button: if there are contributionreards to be transfered, the label will be "redeem for beneificiary", after that it will become simply "redeem".

This behavior corresponds exactly to the semantics of the `redeem` function in `Redeemer.sol`.

I agree though that the label is a bit confusing. This is partly because the term "beneficiary" is ambiguous: it can mean the beneficiary of the protocol rewards, or the beneficiary of the proposal....

**Comment by jellegerbrandy** [comment]
@A-Zak  shall we remove "for beneficiary" from that button, as it is confusing?
