### ISSUE TITLE
wrong "pre boost" button on queued proposal.

### ISSUE THREAD

**Issue by orenyodfat** [daostack/alchemy#739]
![Screen Shot 2019-05-26 at 10 55 59](https://user-images.githubusercontent.com/5994398/58378937-09aa5500-7fa5-11e9-87f0-dee381cf15e6.png)

proposal confidence should be > (not >-=) daothreshold in order to pre boost.

**Comment by orenyodfat** [comment]
@jellegerbrandy @tibetsprague is that already been fixed ?

**Comment by jellegerbrandy** [comment]
yes

**Comment by orenyodfat** [comment]
this bug is still valid 
see https://alchemy.daostack.io/dao/0x440583455bcd85ab2bd429c015d3aabcae135f0a/scheme/0x949943d31b8db2987783563573da3a573ac93b6406ccabe614b89d462fc69965

**Comment by dkent600** [comment]
The PreBoost button is visible when `proposalState.upstakeNeededToPreBoost < 0`.

It seems that `upstakeNeededToPreBoost >= 0` is expected to mean that `score(_proposalId) <= confidenceThreshold`, in other words, that preboosting won't happen.

I think that if there is an error it is in how [this client lib code](https://github.com/daostack/client/blob/6d2a9bf719cba9d88c0900a3b8a9d7fc448470ce/src/proposal.ts#L512) is computing `upstakeNeededToPreBoost`.

The client lib test code that might confirm the logic is currently commented out.

@jellegerbrandy

**Comment by dkent600** [comment]
Client lib ticket:  https://github.com/daostack/client/issues/415

**Comment by dkent600** [comment]
@orenyodfat It is not possible to see what was happening in your latest report above, since the data at the url you gave has now completely changed.  A screenshot would have been much better, one that is very clear about what was incorrect.  In the meantime, if you have any clues you can give about what precisely was happening that should not have, please let us know here, thanks.

**Comment by dkent600** [comment]
I don't honestly find anything wrong in the client lib computations.  I don't see much wrong with the Alchemy UI code either, though I have addressed a few things in [this PR](https://github.com/daostack/alchemy/pull/1482). Otherwise, not knowing what is happening in the GUI, I can't really go much further.

**Comment by orenyodfat** [comment]
looks like this it solved.
https://alchemy-staging-rinkeby.herokuapp.com/dao/0xb1fc05feeacef32bc23b8fcde34080047f55954f/scheme/0xc1234cb878315f474ef56c1ca73c8d4b7419128b8bf09a31eb9a66c80234155c 
<img width="751" alt="Screen Shot 2020-03-08 at 13 54 20" src="https://user-images.githubusercontent.com/5994398/76162233-5b8f2680-6144-11ea-9ca3-49f917b35acb.png">

**Comment by orenyodfat** [comment]
so lets close it till it will popup again :)

**Comment by dkent600** [comment]
@orenyodfat It is still not clear what was the bad behavior that you were seeing.
