### ISSUE TITLE
wrong decimals with usdc reward proposal

### ISSUE THREAD

**Issue by orenyodfat** [daostack/alchemy#795]
see https://github.com/daostack/arc/issues/642

does alchemy read the token decimals when setting the external token reward value ?

**Comment by jellegerbrandy** [comment]
yes, it does now, but the proposal may have been created before we fixed that.

according to the [subgraph](https://subgraph.daostack.io/subgraphs/name/v20/graphql?query=%7Bproposal%20(id%3A%220x518f141328e36c4d24f2a1f03eebea502ca5ff7900fd735732d4dd3e2d5d095e%22)%7B%0A%20%20%0A%20%20id%0A%20%20contributionReward%20%7B%0A%20%20%20%20externalToken%0A%20%20%20%20externalTokenReward%0A%20%20%7D%0A%7D%7D) 
the proposal is actually for 1000000000000000000 USDC, which is 1^18, so that seems to correct.

This is an error in the unput form, and should have been fixed (right @tibetsprague ?)

There is, however, an error int he representation. The form shows that the reward is 10^6, but this should be 10^18 / 10^6 = 10^10

![image](https://user-images.githubusercontent.com/1306173/60005067-14244100-966e-11e9-913e-a449c03aeff9.png)

**Comment by tibetsprague** [comment]
this proposal must have been created before we checked the decimals when creating the proposal. since USDC uses 6 decimals the value on the blockchain is wrong.

**Comment by tibetsprague** [comment]
@orenyodfat  im not really sure how to handle this specific situation, do we ask them to create a new proposal?

**Comment by orenyodfat** [comment]
I guess that if alchemy read the token decimals when setting the external token reward value, we can close this issue.

**Comment by leviadam** [comment]
On creating new proposals this is now fixed. And there is nothing much we can do about tge old ones. Closing.
