### ISSUE TITLE
Transaction construction doesn't allocate enough gas

### ISSUE THREAD

**Issue by sethfork** [daostack/alchemy#826]
Similar to #627 

I'm unable to vote on [this proposal](https://alchemy.daostack.io/dao/0x294f999356ed03347c7a23bcbcf8d33fa41dc830/proposal/0x5a4ad524ea6ac74ec10bc1844c842f59ab944c5ca0a890b927a327cbe38920e3).

Expected Behavior:
- Metamask popup prompts for confirmation.

Actual behavior:
- No Metamask popup
- Toast error indicator is displayed
`FAILURE | ERROR`
`Vote: transaction failed :-(`
- Error in console
`MetaMask - RPC Error: gas required exceeds allowance or always failing transaction`
```javascript
code: -32000
message: "gas required exceeds allowance or always failing transaction"
```

**Comment by jellegerbrandy** [comment]
Thanks for opening an issue :-)

I'd guess it is more probable that the problem was the "always failing transaction", and not the gas estimate (and certainly not the gas price, as in 627). You made this issue roughly abut the time that the proposal was executed and not voteable anymore, so that could have been it.

There is definitly a bug here: we should show an informative error message here. But we do not know which one :-)
