### ISSUE TITLE
Unable To Execute Scheme Removal Proposals

### ISSUE THREAD

**Issue by dOrgJelli** [daostack/alchemy#918]
I am unable to execute the following scheme removal proposals:
https://alchemy.daostack.io/dao/0xbe1a98d3452f6da6e0984589e545d4fc25af7526/proposal/0x21cc40c5587fec1dd138391849be93fcb6decd647ecd54be9f60fe28a593489d
https://alchemy.daostack.io/dao/0xbe1a98d3452f6da6e0984589e545d4fc25af7526/proposal/0x84e855e489ac88923ec0d130656566109c79fa23b0f110e84a0e0c97f3a11255

**Comment by jellegerbrandy** [comment]
proposalId: 0x21cc40c5587fec1dd138391849be93fcb6decd647ecd54be9f60fe28a593489d

[these are the proposal data in the subgraph](https://subgraph.daostack.io/subgraphs/name/v23/graphql?query=%7B%20proposal%20(id%3A%20%220x21cc40c5587fec1dd138391849be93fcb6decd647ecd54be9f60fe28a593489d%22)%7B%0A%20%20id%0A%20%20stage%0A%20%20votingMachine%0A%20%20executedAt%0A%20%20boostedAt%0A%20%20closingAt%0A%20%20genesisProtocolParams%20%7B%0A%20%20%20%20boostedVotePeriodLimit%0A%20%20%7D%0A%20%20schemeRegistrar%20%7B%0A%20%20%20%20decision%0A%20%20%20%20schemeToRemove%0A%20%20%20%20%0A%20%20%7D%0A%20%20winningOutcome%0A%20%20%0A%7D%7D(

schemeRegistrar is here: https://etherscan.io/address/0x0f736ec150749f8064fc96626eb36607ebad97e2

protocol is here: https://etherscan.io/address/0x374026a48d777cb0ffdccdb9a919c0aa7ce8a0fc

**Comment by jellegerbrandy** [comment]
@orenyodfat can you shine a light on this?

**Comment by orenyodfat** [comment]
@dOrgJelli  the proposal cannot be executed because the scheme registrar has wrong permission (0x00000001  ) in dOrg dao.
scheme registrar should have at least 0x00000002 permission to be able to register/unregister other schemes with less or equal permissions.
 see https://github.com/daostack/arc/blob/master/contracts/controller/Controller.sol#L21.
We are usually giving it full permission 0x1f. 
The scheme permission can be read via https://etherscan.io/address/0x809416858a4d0caa83a660c54b59c4180c6d1be3#readContract .

As fat as I remember this dao was not deployed by daostack.

yes, we might update the scheme registrar to separated the proposal execution (decision in the voting machine) from the actual execution (register/unregister) to enable execution of the proposal in the voting machine ...though this is not the case currently.

- it is important to audit(and test) dao setup  after deploying it to prevent such mistakes.
- at the current state dorg dao can not be updated unless it is forked are redeployed.

**Comment by dOrgJelli** [comment]
@orenyodfat thank you for the explanation, makes total sense, whoops XD

I'm thinking that I'll fix this by:
1. Deploying new non-universal Controller contract pointing at our existing Avatar.
2. Manually register the SchemeRegistrar and ContributionReward schemes.
3. Remove myself as a scheme.
4. Execute a controller upgrade in the dOrg DAO.
